### ISSUE TITLE
jakartanet

### ISSUE THREAD

**Issue by trexdbg** [asbjornenge/tezos-randomizer#2]
Hi !
An upgrade to jakartanet is in product ?
Thank you :)

**Comment by asbjornenge** [comment]
@trexdbg I think perhaps, with the new ghostnet, I will manange mainnet + ghostnet. If you require on another testnet you are free to deploy it yourself 👍 

I will update the README once it's deployed on ghostnet 😊

**Comment by trexdbg** [comment]
you right, ghostnet its our future 
many thanks :)

**Comment by asbjornenge** [comment]
Since `ghostnet`  bootstrapped from `ithacanet` the randomizer was already there :star_struck: 

I updated README.md and moved the entropy pushers over :+1:
